### ISSUE TITLE
Pungent Effect crashes the server when saving NBT (1.21)

### ISSUE THREAD

**Issue by ExDrill** [rotgruengelb/MyNethersDelightRefabricated#10]
```
Time: 2024-12-04 20:19:48
Description: Saving entity NBT

java.lang.IllegalStateException: Unregistered holder in ResourceKey[minecraft:root / minecraft:mob_effect]: DeferredHolder{ResourceKey[minecraft:mob_effect / mynethersdelight:b_pungent]}
	at knot//com.mojang.serialization.DataResult$Error.getOrThrow(DataResult.java:287)
	at knot//com.mojang.serialization.DataResult.getOrThrow(DataResult.java:81)
	at knot//net.minecraft.class_1293.method_5582(class_1293.java:311)
	at knot//net.minecraft.class_1309.method_5652(class_1309.java:729)
	at knot//net.minecraft.class_1657.method_5652(class_1657.java:893)
	at knot//net.minecraft.class_3222.method_5652(class_3222.java:412)
	at knot//net.minecraft.class_1297.method_5647(class_1297.java:1922)
	at knot//net.minecraft.class_1130.method_14577(class_1130.java:28)
	at knot//net.minecraft.class_3324.method_14617(class_3324.java:689)
	at knot//net.minecraft.server.MinecraftServer.method_39218(MinecraftServer.java:579)
	at knot//net.minecraft.class_1132.method_39218(class_1132.java:318)
	at knot//net.minecraft.class_1132.method_3748(class_1132.java:96)
	at knot//net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at knot//net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by ExDrill** [comment]
This seems to only happen when receiving pungent from a food.

**Comment by Demadunk** [comment]
I've encountered the bug as well.

**Comment by ChrysanthCow** [comment]
*screams at top of lungs* **POOOOOOOOOOOOOOOORTING LIIIIIIIIIIIIIIIIIIIB!**

Okay, seriously, I was doing something bad with Porting Lib. This will be fixed as soon as the Farmer's Delight Refabricated 3.0.0 compatible update happens.
